kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-local-storage-class
  resources:
    requests:
      storage: 20Gi
